### ISSUE TITLE
When new song is selected, the song jumps to the recommended song.

### ISSUE THREAD

**Issue by wmaiouiru** [zr2d2/Blue-Jay#13]
When a new song is selected from the playlist, the song is jumped by blue-jay to recommended song. 
I believe there should be another step before this happens right ? 
1. User select a new song 
2. Press the blue jay button, one-click-mix!
3. Jump to the recommended song 

instead of 
1. User select a new song 
2. Jump to the recomendded song

**Comment by mathjeff** [comment]
Thank you. Yeah; I agree that it would be better for Bluejay to stop overriding the song choice when the user manually selects a song. The trouble is that we do want Bluejay to control which song is played when the user pushes the skip button, and we haven't yet determined a good way to determine whether the user pushed the skip button or selected a new song. For the moment, you can use the "Turn Off" button, then change the song manually, and push one-click-mix when it's done. If you know of a way to distinguish between the skip button and manual song selection that would be great.

**Comment by mathjeff** [comment]
I was able to fix this, and as a side-effect it created another feature. What I did was I to make it so that whenever the song changes, if the user clicked on a song (single-clicked or double-clicked), then the song will switch to the clicked song. This has the added benefit of allowing the user to request a song to play after the current song by single-clicking it while a song is playing.
